### PR TITLE
Fix carousel failing to lock to remainder slides

### PR DESCRIPTION
**Pull request by saschwartz**
Fix locking issue https://github.com/SSENSE/vue-carousel/issues/243

## Description

Previously, the carousel would calculate offset and lock it to an exact multiple of `slideWidth * currentPerPage`.

For example, say we had 7 slides with 3 per page with 1 extra slide, it would only lock to display slides 1 - 3, 4 - 6, and when on 5 - 7 and the screen was tapped, it would revert to 4 - 6 due to improper offset handling. 

This was solved by ensuring that the remainder slides (5 - 7 in this example) is a valid position for the carousel to lock into.

## Motivation and Context

It solves https://github.com/SSENSE/vue-carousel/issues/243

To replicate the bug fix, add an extra slide to the Vue Play examples (so it doesn't divide evenly by currentPerPage). Now, tapping on the final slide when the carousel is all the way over will not cause it to lock back to the previous page. Whereas previously, as per the issue solved here, that would occur.

## How Has This Been Tested?

Vue Play was used to test the behaviour of the component.

## Screenshots (if appropriate):

N/A 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] I have included a vue-play example (if this is a new feature)

Credit also to @noahlafferty

### CODE REVIEW

**Comment by saschwartz** [comment]
Hi @quinnlangille, I notice that you maintain this repo - any chance you might be able to take a look at this PR?

I see that you have opened https://github.com/SSENSE/vue-carousel/issues/274 for discussing a refactor of the logic entirely - seems great. Though, since our team uses this component in production it'd be wonderful to merge in this fix even in advance of that if you are open to that.

**Comment by quinnlangille** [comment]
Lgtm! Thanks for the fix, it was a serious issue. I’ll leave the current issue open, as a full rewrite of the logic is definitely needed but this is a great patch in the mean time!

**Comment by quinnlangille** [comment]
Regarding your email, I’ve merged this into the current working branch and will release as an rc as soon as possible!

**Comment by saschwartz** [comment]
Unreal thanks!

**Pull request merged**
