### PR TITLE
Fix scrollPerPage

### PR DESCRIPTION
**Pull request by kulaone**
Set scrollPerPage default to true. 
When false, all system move by slides and not by pages. From navigation to pagination including navigateTo.

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @kulaone, this is great! Thanks so much for fixing. I'll check out tomorrow when I'm back in the office, but in the meantime are we able to look into why there is such a big diff in the package-lock? It doesn't seem like you've added any packages, so maybe just `rm` your current one, your node modules and `npm i` to generate a new one

**Comment by kulaone** [comment]
@quinnlangille I remove the package-lock. 
I had some problems with my NPM, sorry for that.

**Comment by quinnlangille** [comment]
No worries @kulaone, going to review and hopefully merge this in later this afternoon

**Comment by kulaone** [comment]
@quinnlangille quick questions I saw that vue-carousel.min.js is not updated in the master.
Did I needed to update it before merging?

**Comment by quinnlangille** [comment]
I updated it with the last release!

**Pull request merged**
