### PR TITLE
fix(slide-active): use breakpointSlidesPerPage instead of perPage for determining Slide's isActive computed property

### LINKED ISSUE #338: Bug: VueCarousel-slide-active with perPageCustom not working correctly
## Bug Report

**Current Behavior**
I am using the perPageCustom attribute to dynamically set the number of slides to either 2, 3, 4 or 5.  For some reason the VueCarousel-slide-active class only gets applied to the first 2 slides, like the number of slides is 2 all the time.

**Input Code and steps to reproduce**
`<carousel
              :navigation-enabled="true"
              :min-swipe-distance="1"
              :per-page-custom="[[0,2], [600,3], [750, 4], [1024, 5]]"
              navigation-next-label="<i class='fas fa-3x fa-angle-right'></i>"
              navigation-prev-label="<i class='fas fa-3x fa-angle-left'></i>">
              <slide
                v-for="product in products"
                :key="product.id">
                <Product
                  :id="product.id"
                  :product-info="product"/>
              </slide>
            </carousel>`

**Expected behavior/code**
The VueCarousel-slide-active class should be applied to all the slides showing no matter how many are showing.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "your": { "config": "here" }
}
```

**Environment**
- Babel version(s): [?]
- Node/npm version: [NPM 5.6.0]
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
capture

### PR DESCRIPTION
**Pull request by yojenkins**
## Description
First-time open source contributor here so please feel free to let me know if I need to provide any more details or test support for this change. 😊

Change Slide component's `isAcitve` computed property to rely on Carousel's `breakpointSlidesPerPage` instead of `perPage`

## Motivation and Context

Fixes #338  

## How Has This Been Tested?

Tested using a vue-play example with the markup from the [jsfiddle](https://jsfiddle.net/we8jbym2/) referenced in #338. Ran the repo's unit tests to ensure no unit test affected by the change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @yojenkins, thanks for making the contribution! This bug has come up in a few different issues recently, so super happy to have the fix. The code looks good to me! If you feel comfortable writing some tests, that would also be pretty helpful. We've just merged in a pretty large test overhaul, so there should be lots of examples to go off of.

The logic in the `isCenter` method is already covered by tests, but for this it would be great to see a regression test covering the appearance of the `VueCarousel-slide-active` on the correct slides. @ashleysimpson is currently leading the test overhaul, so maybe he has some other ideas as well. 

If you're interested in implementing just lemme know and we can help anywhere that's needed! If not, also let me know and I can merge this and write the test myself :rocket:

**Comment by quinnlangille** [comment]
Perfect, looking forward to seeing the results @yojenkins!

**Comment by quinnlangille** [comment]
Hey @yojenkins, tests look great! I'll merge in as soon as travis passes

**Comment by Nfinished** [comment]
Still chasing down why but I believe this broke the `isCenter` property in `Slide.vue`

**Comment by Nfinished** [comment]
Scratch that, looks like that was already broken in v0.17.0, something in here just made it more noticeable.

**Pull request merged**
