### PR TITLE
Add transition hook function

### PR DESCRIPTION
**Pull request by stop2stare**
Add transition end hook. With this hook, we'll be able to do some customized work like initiating the next page.

### CODE REVIEW

**Comment by stop2stare** [comment]
@quinnlangille resolved.

**Comment by stop2stare** [comment]
@quinnlangille OMG, I'm just resolving conflicts... And you merged master.🤣

**Comment by quinnlangille** [comment]
@stop2stare oh no! I can revert if it's an issue, it was just a whitespace difference so I resolved instead of pinging you haha lmk if you want me to undo

**Comment by stop2stare** [comment]
@quinnlangille haha, it's ok. Just merge this PR.

**Pull request merged**
