### PR TITLE
feat(accessibility): use correct aria properties

### PR DESCRIPTION
**Pull request by AdminXVII**
## Description
Based on [aXe](https://www.deque.com/axe/) recommendations, fix accessibility:
 - Use proper roles for the various components (ex: role="button" not needed on buttons).
 - Reorder navigation and pagination to better match the tabbing order.
 - Make navigation accessible by tabbing.
 - Change the HTML elements to better match [W3's recommended organization](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html)

## Motivation and Context
Accessibility of the carousel.

## How Has This Been Tested?
Tested using vue-play in Firefox and Chrome on Linux.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by quinnlangille** [comment]
^ resolved some small conflicts caused by the base branch switch

**Comment by quinnlangille** [comment]
Ah dang looks like this will need a rebase with `v0.17.0`. Do you mind rebasing and pushing back up when you get a sec?

**Comment by AdminXVII** [comment]
Done

**Comment by quinnlangille** [comment]
Perfect @AdminXVII, will merge into the working branch! Thanks for the upgrade 🚀

**Pull request merged**
