### PR TITLE
Adding infinite loop. 

### PR DESCRIPTION
**Pull request by incraigulous**
For issue: https://github.com/SSENSE/vue-carousel/issues/12

### CODE REVIEW

**Comment by japboy** [comment]
anything i can help so that this pr will be released soon?

**Comment by toddlawton** [comment]
@japboy @incraigulous could you please update the tests? we won't be able to merge this with a net coverage decrease. thanks!

**Comment by realtebo** [comment]
Please.... release this feature soon !

**Comment by incraigulous** [comment]
Mirko,

I think the only thing they are waiting on is tests. I'm swamped right now
and will be for the next few months so I don't have any margin.

If you want to write the tests, I bet they would merge it in. It's not that
much code, so it shouldn't be too much effort.

I've been using this branch in production since I wrote it, so it shouldn't
have any bugs. Still needs the tests written though.

**Comment by incraigulous** [comment]
I think we should go with https://github.com/SSENSE/vue-carousel/pull/62 instead of this instead of mine. @admin, this is my PR, would you please reject and close it in favor of @julbra's?

**Pull request closed without merging**
