### PR TITLE
feat(event): emit navigation-click and pagination-click from Carousel

### PR DESCRIPTION
**Pull request by darraghenright**
## Description

Since Vue events do not bubble up through the component tree, the `navigationclick` and `paginationclick` events from `Navigation` and `Pagination` that are emitted into the `Carousel` component cannot be listened to in userland code.

This PR adds `navigation-click` and `pagination-click` events, which are emitted from and can be listened to on the `Carousel` component:

```js
<Component @navigation-click="onNavigationClick" @pagination-click="onPaginationClick"/>
```
These events are in kebab-case, in line with Vue's recommended naming scheme for [Custom Events](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names).

Each emitted event includes a value: 

* `navigation-click` is emitted with the current direction (`backward` or `forward`)
* `pagination-click` is emitted with the current `pageNumber`

These new events delegate from the existing "internal" events—`Navigation@navigationclick` and `Pagination@paginationclick`. The behaviour and naming of these events have not been changed.

## Motivation and Context

There were some questions about these events in at least one issue, so I concluded these are anticipated and potentially useful events to make available to end-users.

It does not fix any open issues as far as I am aware, although there are some questions in tickets about this functionality.

## How Has This Been Tested?

Implemented code, created and sanity checked Vue Play examples. Existing unit tests passed.

## Screenshots (if appropriate):

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [x] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @darraghenright, adding some tests would definitely be helpful! @ashleysimpson is working on a test refactor right now, maybe we can sync on what/how we should test here?

**Comment by darraghenright** [comment]
Sounds great. It'd certainly be good to test for the emitted events, and their values, so I am all ears on that!

**Comment by darraghenright** [comment]
@quinnlangille I had a look at `package.json` and I see that Vue Test Utils are installed:

```js
 "@vue/test-utils": "^1.0.0-beta.26",
```

I'm new to Vue Test Utils but I read through the docs this weekend, and it looks ideal, particularly for testing events. So I am happy to write some tests.

@ashleysimpson Should I wait until you have finished your test refactor before I add tests to my PR?

Thanks folks 😎

**Comment by ashleysimpson** [comment]
@darraghenright if you rebase (or merge) now you should be able to see the new testing structure. You can add the new tests under the appropriate describe or add a new one if you need. I can check over your changes whenever you are ready.

**Comment by quinnlangille** [comment]
Hey @darraghenright, finally merging this. It's currently going into our next release candidate, I'll ping you when it's released! Thanks a million for the contribution, and sorry for the delay!

**Comment by darraghenright** [comment]
He @quinnlangille — fantastic! I've been using the library in a few places now, so I am delighted to have contributed :)

**Comment by quinnlangille** [comment]
@darraghenright glad to hear - Don't be a stranger if you find the time to make another contribution!

**Comment by darraghenright** [comment]
Definitely!

**Pull request merged**
