### PR TITLE
Feature: Add v-model functionality for currentPage

### PR DESCRIPTION
**Pull request by ccarstens**
By adding a value property and an input even emission to watch.currentPage() v-model functionality can be achieved. This way it's handy and easy to control the current page from the outside while getting the index number conveniently fed back

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @ccarstens, this is a cool feature! If you're currently using this, any chance you could add an example of it working or link to a jsfiddle?

**Comment by ccarstens** [comment]
Hey @quinnlangille,

Thanks for the feedback!
Yeah for sure I’ll prepare a fiddle tonight or tomorrow. 
Best 
ccarstens

**Comment by ccarstens** [comment]
Hi @quinnlangille,
I added a vue play example to showcase the new functionality.
best,
ccarstens

**Comment by DreaMinder** [comment]
thanks, very useful feature. 
I use your fork in my project, hope it will be merged soon.

**Comment by quinnlangille** [comment]
Hey! Thanks for updating the examples - I was on holiday for the earlier part of this week, so didn't see the changes until now. Pr looks good to me, I'll merge it in with the next release :~)

**Comment by dangreaves** [comment]
This would be really helpful for us.

Our specific use case is to build a custom paginator component which sits outside the slider itself.

Using `v-model` would be super helpful here 👍

**Comment by quinnlangille** [comment]
@dangreaves going to merge this in today! I've started to carve out Wednesday afternoons on my schedule for carousel maintenance - this will hopefully facilitate better response time to PRs than the "ill merge them in my spare time" approach lol

**Comment by quinnlangille** [comment]
Merging this in now - should be released by mid-day Montreal time!

**Pull request merged**
