### PR TITLE
Fix: Slide-click isTouch reference

### PR DESCRIPTION
**Pull request by epartipilo**
### Note ###
This is a documentation improve that get the fix line made by @JeanBarriere [here](https://github.com/SSENSE/vue-carousel/pull/185)

### Details ###
- Updated documentation to show how to use the event

### CODE REVIEW

**Comment by epartipilo** [comment]
@quinnlangille I'm on it

**Comment by epartipilo** [comment]
@quinnlangille Ready, just some documentation

**Comment by quinnlangille** [comment]
Perfect thanks @epartipilo! Will merge right now 🎉

**Comment by epartipilo** [comment]
Prefect, thank you @quinnlangille

**Comment by lennoximus** [comment]
Finally, thank you!

**Pull request merged**
