### PR TITLE
test(props): adjustableHeight & adjustableHeightEasing

### PR DESCRIPTION
**Pull request by josephting**
## Description
Explanation of my approach in writing these test cases can be found [here](https://github.com/SSENSE/vue-carousel/issues/143#issuecomment-450297594).

Since master branch is latest now, I'm basing my work here off of master branch until a dev branch is created for upcoming release.

## Motivation and Context

First attempt to increase code coverage (albeit to no success).
Would appreciate guidance and help by reviewing this.

## How Has This Been Tested?

Main test here I think is checking for the computed value of `transitionStyle`.

I've also included the snapshot but I don't think this is effective here since `transition` css style is not included for some reason. Same applies to every other snapshots. Transition style just don't seem to get included in the snapshot.

Same applies to the snapshot before switching to jest-serializer.

```javascript
exports[`Carousel should apply custom slides per page when responsive param provided 1`] = `
".VueCarousel-wrapper
  .VueCarousel-inner(role='listbox', style='transform: translate(0px, 0); visibility: hidden; height: auto;')
|  
.VueCarousel-pagination(style='display: none;')
  ul.VueCarousel-dot-container(role='tablist')
// 
"
`;
```
[carousel.spec.js.snap @ v0.16.2](https://github.com/SSENSE/vue-carousel/blob/v0.16.2/tests/client/components/__snapshots__/carousel.spec.js.snap)

## Types of changes

- [ ] ~Bug fix (non-breaking change which fixes an issue)~
- [ ] ~New feature (non-breaking change which adds functionality)~
- [ ] ~Breaking change (fix or feature that would cause existing functionality to not work as expected)~

## Checklist:

- [x] My code follows the code style of this project.
- [ ] ~My change requires a change to the documentation.~
  - [ ] ~I have updated the documentation accordingly.~
- [ ] ~I have included a vue-play example (if this is a new feature)~

### CODE REVIEW

**Comment by josephting** [comment]
@quinnlangille Hmm.. Seems like these test cases managed to add some line hits but not the coverage rate.
Your guidance will be very much appreciated. 🙇

**Comment by quinnlangille** [comment]
@josephting was unplugged for the new year over the weekend. Sorry for the delay - will be back in regular contact now. Hmmm.. We've been experiencing some weirdness with coveralls internally as well, lemme run some checks locally and report back. 

The only way more lines wouldn't equal more coverage percentage is if the percentage was below coveralls rounding threshold, which doesn't make sense for a project this size so something is amiss

**Comment by josephting** [comment]
@quinnlangille No worries and happy new year! 🎆
I don't think it's something related to coveralls as coveralls is merely reporting back with the lcov generated which is what I'm looking at when developing anyway before pushing any code.

With that said, I still don't get why codes that should have been covered stayed uncovered to be honest.

**Comment by quinnlangille** [comment]
Yeah you're right, definitely not coveralls related I just ran both master and your branch locally. Maybe there is an issue with coverage config, because you've clearly added tests that are covering untouched functionality. I'll investigate tonight and see if I can find anything code related :octocat: In the mean time, tests look good! I'm comfortable merging this whenever, if I can't get a conclusive response by end of day on tests then I'll just merge and debug later

**Comment by quinnlangille** [comment]
Oh also, I should mention that if you want to see a more indepth coverage report you can navigate to `/coverage/client` and open `index.html` in your browser. It will show line by line coverage visually

**Comment by josephting** [comment]
Thank you, @quinnlangille. Yeah, I'm currently looking at the `index.html` inside `coverage/client/lcov-report`. I suppose it's the same as the one in `coverage/client` 🤔 

I've made sure that the configs are configured correctly before creating the PR. Unless there is something that I don't have knowledge of.

**Comment by quinnlangille** [comment]
Nah the configs look good, checked with @ashleysimpson today and we both concluded the existing coverage is from a vague test. Will merge this in now and work on our end to try and eliminate the noise in the coverage report! Thanks for the work on this, and sorry it took so long to get merged in, now that the holiday season is over we should be moving at a regular pace ⏩

**Pull request merged**
