### PR TITLE
Add jest-serializer-vue as snapshot serializer

### PR DESCRIPTION
**Pull request by josephting**
**Please merge either this or #343. (Only one of the two)**

## Description

Replacing the custom jade snapshot in [`tests/client/utils.js`](https://github.com/SSENSE/vue-carousel/blob/master/tests/client/utils.js) with [jest-serializer-vue](https://github.com/eddyerburgh/jest-serializer-vue) as discussed in #339.

- Add jest-serializer-vue to package.json
- Remove html2jade from package.json
- Delete tests/client/utils.js
- Replace all snapshot assertion to use jest snapshot assertion
- Some sync tests were converted to async tests in order to `$nextTick` for the dom changes to take place when Slide are loaded to the slots.

## Motivation and Context

Hoping to lower the barrier for entry in using snapshots for unit tests.
Also making it easier to review pull requests with snapshot changes.

## How Has This Been Tested?

Reviewed all snapshot changes are of the same structure as previous snapshots in jade.
Tests pass successfully.

## Types of changes

- [ ] ~Bug fix (non-breaking change which fixes an issue)~
- [x] New feature (non-breaking change which adds functionality)
- [ ] ~Breaking change (fix or feature that would cause existing functionality to not work as expected)~

## Checklist:

- [x] My code follows the code style of this project.
- [ ] ~My change requires a change to the documentation.~
  - [ ] ~I have updated the documentation accordingly.~
- [ ] ~I have included a vue-play example (if this is a new feature)~

### CODE REVIEW

**Comment by quinnlangille** [comment]
Ah, looks like there is some conflict caused by an update to master. I think your branch just needs a rebase!

**Comment by josephting** [comment]
Looks like a simple rebase wasn't enough. I'll spend some time giving this a final check today.

**Comment by josephting** [comment]
@quinnlangille Had to do some clean up from previous PRs.

- Tags changes made in #349 
- Pre jest-serializer-vue test in #322 

Added a new commit to address those instead for better visibility.

This PR is ready to be merged now. 🚀

**Comment by quinnlangille** [comment]
Perfecttt thanks so much @josephting, sorry about merging ontop of yours. Will try to avoid that in the future. Merging now 🚀

**Pull request merged**
