### PR TITLE
feat(carousel): add thumbnails slot

### PR DESCRIPTION
**Pull request by seifsay3d**
addresses #111, still need to add thumb.spec.js but wanted to make sure I'm headed in the right direction.

### CODE REVIEW

**Comment by drxwskx** [comment]
@seifsay3d Just glanced over your code but I'm uncertain of the purpose. What are we trying to achieve with the thumbnail. Placeholder image?

**Comment by quinnlangille** [comment]
@seifsay3d the thumbnails will replace the pagination buttions, like in your liked example? Or this is what you plan to implement?

**Comment by seifsay3d** [comment]
@quinnlangille of course achieving similar functionality to flex-slider would be great, but I was thinking of implementing 
1 - thumbnail place holder
2- ability to click on a thumbnail to change carousel's current page
and if that went well we can add
3- scroll in thumbnails with next/previous buttons.

**Comment by quinnlangille** [comment]
@seifsay3d yeah this looks good, add some tests and we'll look at adding it into the next release (following 0.6.6). Also, if you feel like implementing the clickable thumbnail I think it would be a great feature!

**Pull request closed without merging**
