### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rkomiyama**
Current README section for "Development" is slightly ambiguous.

## Description

Added in the necessary lines for `getplay` for devs who have never used it before.

## Motivation and Context

Current README section for "Development" is slightly ambiguous.

## How Has This Been Tested?

N/A

## Screenshots (if appropriate):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @rkomiyama, thanks for the update! I'm not sure it's necessary though, `getplay` isn't required to run`vue-play`. The project installs `vue-play` and runs it as a locally installed dependency. Am I missing something here?

**Comment by quinnlangille** [comment]
@rkomiyama can you send error output. I don't have `getplay` installed and everything works on my end. What OS are you running on?

**Comment by rkomiyama** [comment]
I'm running macOS 10.12.6.

Here's the error message:
```
➜  vue-carousel git:(master) npm run dev

> vue-carousel@0.15.0 dev /Users/weboffice/git/vue-carousel
> vue-play start --standalone


vue-play-start.js(1) does not exist, try --help

/Users/weboffice/git/vue-carousel/node_modules/cac/dist/cac.common.js:221
      throw err
      ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/weboffice/git/vue-carousel/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/weboffice/git/vue-carousel/node_modules/extract-text-webpack-plugin/index.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-carousel@0.15.0 dev: `vue-play start --standalone`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-carousel@0.15.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/weboffice/.npm/_logs/2018-10-24T13_53_59_151Z-debug.log
```

**Comment by rkomiyama** [comment]
Never mind, it seems like it was an issue with my npm. Closing this PR.

**Pull request closed without merging**
