### PR TITLE
feat(carousel): Count slides by custom tag name

### PR DESCRIPTION
**Pull request by ashtonmeuser**
Enable components to extend slide. Carousel considers child components slides if component name matches `tagName`.

## Description
Add `tagName` property to carousel. Defaults to "slide", which is currently used. Counts child slide components by matching whole tag name (regex `^vue-component-\\d+-${this.tagName}$` used). Added test.

## Motivation and Context
When wrapping slides, the wrapping components tag name (not necessarily "slide") prevents it from being considered a slide within a carousel. This results in 0 extended slides showing in carousel. This circumvents requiring extending components to have the name "slide" (of particular annoyance if using ESLint's default preference of PascalCase component names).

If the carousel is intended to have similarly structured slides, there is a lot of boilerplate required. This change allows structuring a component that wraps slide. A simple title or body property could then be supplied to each extended slide.

## How Has This Been Tested?
Added test to [carousel.spec.js](https://github.com/SSENSE/vue-carousel/blob/master/tests/client/components/carousel.spec.js). Test adds three slides to a carousel, two of which are extend slide. The carousel is set to match the tag names of the extended slides. It should only count extended slides.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [ ] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by csmoakpax8** [comment]
@ashtonmeuser This would be great!
@quinnlangille Do you have any issues with merging this?

**Comment by ashtonmeuser** [comment]
@quinnlangille Bump. Is there anything you'd like me to add to encourage this to be merged?

**Comment by quinnlangille** [comment]
Hey @ashtonmeuser, sorry for the delay on this one! We've been crazy busy at the office with year end wrap-up and I've been delinquent on PR reviews. This is a brilliant feature! We had something similar planned internally, but this will meet the needs for sure. I'll merge this into our working branch for next release, it should be out late this week or early next! 🚀 

Thanks for the contribution, and again sorry for the delay on review! We'll be more on-top of things going forward :octocat:

**Comment by quinnlangille** [comment]
^ just resolved some small merge conflicts in the build files.

**Comment by ashtonmeuser** [comment]
Will do. I must have fallen behind.

**Comment by quinnlangille** [comment]
Yeah we merged a few other PRs into the working branch since, so will just need to catch up with those. It's a few commits ahead of master

**Comment by ashtonmeuser** [comment]
@quinnlangille Turned out to be the migration to Vue Test Utils. Fixed.

**Comment by quinnlangille** [comment]
Ahhh perfect @ashtonmeuser, thanks for branch update 👍 Will merge now :octocat:

**Pull request merged**
