### PR TITLE
feat(pagination) added an option to add custom title in pagination bu…

### PR DESCRIPTION
**Pull request by VojtechKlos**
Allow custom titles in carousel pagination.

## Description
Extends on the pull request #263 allowing specifying custom title by passing the title prop to the slide component.

## Motivation and Context
Sometimes you need custom titles instead of just "Item 0" etc...

## How Has This Been Tested?
Just manually. I am not sure how and if to write tests for this.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @VojtechKlos thanks for making the contribution, looks like your branch needs a rebase on `v0.17.0` before we can review! There's a lot of noise on there from other PR, the rebase should fix that up.

**Comment by quinnlangille** [comment]
Hey @VojtechKlos, thanks for the cleanup! I'll merge in now 🚀

**Comment by VojtechKlos** [comment]
@quinnlangille hey, thanks for merging my pr. When is it planned to release version 0.17?

**Comment by quinnlangille** [comment]
@VojtechKlos should be sometime next week! I'll make a release when it's out, if you're watching the repo you should get a notification :octocat:

**Comment by tomifis** [comment]
How can i make the title not appearing? I mean i don't want the title tag when hovering dots

**Pull request merged**
