### PR TITLE
fix(WIP): fix pageCount when scrollPerPage is true

### PR DESCRIPTION
**Pull request by RyanLiu0235**

### CODE REVIEW

**Comment by stop2stare** [comment]
This PR is related to issue #178 .

**Comment by quinnlangille** [comment]
Based on the discussion in #178, should I hold off on merging this?

**Comment by stop2stare** [comment]
@quinnlangille yes please. I'm still working on it.

**Comment by ashleysimpson** [comment]
@RyanLiu0235 I am going to close this, please feel free to open it again if you want to continue working on it

**Pull request closed without merging**
