### PR TITLE
Fixed typo in computed property

### PR DESCRIPTION
**Pull request by utkarshnag**
Changed computed property name from 'pagniation' to 'pagination'. Two instances were found. Both were updated.

### CODE REVIEW

**Comment by quinnlangille** [comment]
@utkarshnag wow great find, this was probably causing some actual issues I can't believe no one noticed! Do you mind updating tests on your end and pushing back up, you can just run `npm run test -u` to update the snapshots. Thanks a million!

**Comment by utkarshnag** [comment]
I ran the command and it passed all the test cases. Am I supposed to do anything else as well?

$ npm run test -u

> vue-carousel@0.11.0 test C:\Users\hp\Desktop\Forks\vue-carousel
> npm run test:client


> vue-carousel@0.11.0 test:client C:\Users\hp\Desktop\Forks\vue-carousel
> jest --config tests/client.jest.json --forceExit

 PASS  tests\client\components\carousel.spec.js
  Carousel
    √ should mount successfully (160ms)
    √ should unmount successfully (5ms)
    √ should be unable to advance backward by default (3ms)
    √ should be unable to advance forward by default (no slides added) (2ms)
    √ should apply custom slides per page when responsive param provided (4ms)
    √ should fall back to default slides per page when no responsive param provided (17ms)
    √ should apply default carousel width when element has 0 width (2ms)
    √ should apply 200px carousel width when element has 200px width (3ms)
    √ should go to second slide when we have odd number of slides and recompute carousel width (14ms)
    √ should register 0 slides when 0 slides are added to the slots (3ms)
    √ should register 3 slides when 3 slides are added to the slots (7ms)
    √ should decrease current page number by 1 when advance page backward is called (9ms)
    √ should increase current page number by 1 when advance page is called (7ms)
    √ should increase current page number by 1 when advance page is called with a non "backward" argument (6ms)
    √ should decrease current slide number by 1 when advance slide backward is called (8ms)
    √ should loop back to the start when loop is true and advance page non "backward" is called from the last page (8ms)
    √ should loop to the end when loop is true and advance page "backward" is called from the first page (11ms)
    √ should begin autoplaying when option specified (7ms)
    √ should reset autoplay when switching slide without autoplayHoverPause (7ms)
    √ should not reset autoplay when switching slide with autoplayHoverPause (8ms)

 PASS  tests\client\components\navigation.spec.js
  Navigation
    √ should mount successfully (51ms)
    √ should render a next button (16ms)
    √ should render a prev button (14ms)
    √ should trigger page advance when next is clicked (10ms)
    √ should trigger page advance backward when prev is clicked (15ms)

 PASS  tests\client\components\slide.spec.js
  Slide
    √ should mount successfully (35ms)

Test Suites: 3 passed, 3 total
Tests:       26 passed, 26 total
Snapshots:   24 passed, 24 total
Time:        2.346s, estimated 3s
Ran all test suites.

**Comment by utkarshnag** [comment]
It says that there's nothing to commit i.e. running the test didn't change anything/ update the snapshots. I checked the snapshots folder and found that there was no file for pagination. Maybe that's why?

There are 3 spec.js.snap files in the snapshots folder. Each for carousel, navigation and slide.

**Comment by utkarshnag** [comment]
Also @quinnlangille thanks for helping out! I'm gonna try helping out with some other 'good first issues'. Fingers crossed.

**Comment by quinnlangille** [comment]
Ah, now that I'm looking at other PRs it seems this is an issue with our package.json. It'll be resolved once I merge in #266! Once that's in, I'll merge this 👨‍💻 

And that's great! Feel free to comment on any specific open issue and I can help out

**Pull request merged**
