### PR TITLE
Vue code chunks syntax highlighting fix

### PR DESCRIPTION
**Pull request by Igloczek**

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @Igloczek, update looks good here thanks for that. There seems to be a problem with travis though, once it's resolved on their end I'll restart your build

**Comment by Igloczek** [comment]
Travis env issues are fixed in #266, restarting build will not help ;)

**Comment by quinnlangille** [comment]
Ah, I was guessing it was an issue with travis. I'll debug the yarn stuff and see if I can fix myself,  #266 will work in the mean time!

**Comment by Igloczek** [comment]
@quinnlangille I can extract just code related to fixing failing builds if you want

**Comment by quinnlangille** [comment]
I think it's fine to leave in #266, I'll merge that once the comments are addressed, and then yours once the travis build is successful

**Pull request merged**
