### PR TITLE
Ability to disable swipe completely or by breakpoints

### PR DESCRIPTION
**Pull request by jCrip**
Add flag to disable swipe.
This can be true, the default value, to enable swipe, false to disable swipe or an array of arrays to disable  swipe by screen resolution. Each array is formatted as [x, y] where x is the browser width, and y is true or false.

### CODE REVIEW

**Comment by pycarlos** [comment]
It's the same #89, ok this is better

**Comment by pycarlos** [comment]
@SSENSE Can you check this pls?

**Comment by drxwskx** [comment]
@pycarlos I'll be reviewing the PR's in the coming weeks, thanks for your patience

**Comment by pycarlos** [comment]
Thank you, but please do not merge. Because #89 is better.

**Comment by vanderb** [comment]
Since i dont see any changes in the docs, I disable the pointer-events via css.
This should work.

```
.VueCarousel-wrapper {
  pointer-events: none;
}
```

**Comment by helloromero** [comment]
Did anyone find a way to disable swipe yet? need a JS solution

**Pull request closed without merging**
