### PR TITLE
feat(standard): adding touchDrag prop to block touch dragging

### PR DESCRIPTION
**Pull request by NickMcBurney**
## Description

1. Added new prop `touchDrag`, mirroring naming/settings of mouseDrag.
2. Adding `touchDrag` to the `if (isTouch || mouseDrag) onStart` trigger, meaning the user can turn off touch dragging on mobile devices by setting both `touchDrag` and `mouseDrag` bool to `false`.

## Motivation and Context
I needed this functionality for a project I'm working on, allowing me to block users from moving slides with touch drag, meaning slides can only move using builtin methods.

## How Has This Been Tested?
Passed Linting & Automated Tests
Manual Testing: Duplicated build output to a local project and tested in Chrome Dev Tools and on Android Mobile Device. 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
  - [x ] I have updated the documentation accordingly.
- [ ] I have included a vue-play example (if this is a new feature)

### CODE REVIEW

**Comment by quinnlangille** [comment]
Hey @NickMcBurney, thanks for this! Really great implementation, a lot more simple than what I was thinking 👍 We use yarn on the project vs npm, so don't you mind removing the `package-lock.json` (and also, if you have an extra second can you add it to the `.gitignore`). 

Once that's done I'll merge it in! :octocat:

**Comment by NickMcBurney** [comment]
Thanks @quinnlangille, thought it best to keep it as simple as possible. I've just committed again with the lock file removed and added to .gitignore

**Comment by quinnlangille** [comment]
Perfect thanks! Will merge in asap

**Comment by NickMcBurney** [comment]
@quinnlangille, do you know when you'll be able to get this merged in? Could do with functionality for a project and I'd prefer to not use my local version.

**Comment by quinnlangille** [comment]
Hey @NickMcBurney, I'm working on another feature for the release currently. I can merge it into a feature branch and publish as a release-candidate if you'd like to use it now though

**Comment by quinnlangille** [comment]
Release and tagged here: https://github.com/SSENSE/vue-carousel/tree/v0.16.0-rc1

Available on npm as `vue-carousel@v0.16.0-rc1`

**Pull request merged**
